src/main/java/mb/UserMB.java
package mb;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import model.User;

@SessionScoped
@ManagedBean(name = "userMB")
public class UserMB implements Serializable {
	public static final String INJECTION_NAME = "#{userMB}";
	private static final long serialVersionUID = 1L;

	private User user;

	public boolean isAdmin() {
		return user.isAdmin();
	}

	public boolean isDefaultUser() {
		return user.isUser();
	}

	public String logOut() {
		getRequest().getSession().invalidate();
		return "/pages/public/login.xhtml";
	}

	private HttpServletRequest getRequest() {
		return (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}

src/main/webapp/pages/protected/templates/left.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:body>
	<ui:composition>
		<h:form>
			<p:commandButton styleClass="menuButton" icon="ui-icon-arrowstop-1-e" rendered="#{userMB.admin or userMB.defaultUser}" action="/pages/protected/defaultUser/defaultUserIndex.xhtml" value="#{bundle.personPlural}" ajax="false" immediate="true" />
			<br />
			<p:commandButton styleClass="menuButton" icon="ui-icon-arrowstop-1-e" rendered="#{userMB.admin}" action="/pages/protected/admin/adminIndex.xhtml" value="#{bundle.dogPlural}" ajax="false" immediate="true" />
			<br />
		</h:form>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/protected/templates/master.xhtml
<?xml version="1.0" encoding="UTF-8" ?>  
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>CrudJSF</title>
	<h:outputStylesheet library="css" name="main.css" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</h:head>

<h:body>
	<f:view contentType="text/html; charset=UTF-8" encoding="UTF-8" >
		<div id="divTop" style="vertical-align: middle;">
			<ui:insert name="divTop">
				<ui:include src="top.xhtml" />
			</ui:insert>
		</div>

		<div id="divLeft">
			<ui:insert name="divLeft">
				<ui:include src="left.xhtml" />
			</ui:insert>
		</div>

		<div id="divMain">
			<p:growl id="messageGrowl" />
			<ui:insert name="divMain" />
		</div>
		
		<h:outputScript library="javascript" name="jscodes.js" />
	</f:view>
</h:body>
</html>

src/main/webapp/pages/protected/templates/top.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
   <h:body>   
     <ui:composition>
     	<div id="topMessage">
     		<h1>
     			<h:form>
		     		#{bundle.loginWelcomeMessage}: #{userMB.user.name} | <p:commandButton value="#{bundle.logOut}" action="#{userMB.logOut()}" ajax="false" style="font-size: 20px;" />
     			</h:form>
     		</h1>
     	</div>
     </ui:composition>   
   </h:body>
</html>