src/main/java/mb/PersonMB.java
package mb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import com.sun.faces.context.flash.ELFlash;

import facade.DogFacade;
import facade.PersonFacade;
import model.Dog;
import model.Person;

@ViewScoped
@ManagedBean
public class PersonMB extends AbstractMB implements Serializable {
	private static final long serialVersionUID = 1L;

	private static final String SELECTED_PERSON = "selectedPerson";

	private Dog dog;
	private Person person;
	private Person personWithDogs;
	private Person personWithDogsForDetail;

	private List<Dog> allDogs;
	private List<Person> persons;

	private DogFacade dogFacade;
	private PersonFacade personFacade;

	public void createPerson() {
		try {
			getPersonFacade().createPerson(person);
			closeDialog();
			displayInfoMessageToUser("Created With Sucess");
			loadPersons();
			resetPerson();
		} catch (Exception e) {
			keepDialogOpen();
			displayErrorMessageToUser("Ops, we could not create. Try again later");
			e.printStackTrace();
		}
	}

	public void updatePerson() {
		try {
			getPersonFacade().updatePerson(person);
			closeDialog();
			displayInfoMessageToUser("Updated With Sucess");
			loadPersons();
			resetPerson();
		} catch (Exception e) {
			keepDialogOpen();
			displayErrorMessageToUser("Ops, we could not create. Try again later");
			e.printStackTrace();
		}
	}

	public void deletePerson() {
		try {
			getPersonFacade().deletePerson(person);
			closeDialog();
			displayInfoMessageToUser("Deleted With Sucess");
			loadPersons();
			resetPerson();
		} catch (Exception e) {
			keepDialogOpen();
			displayErrorMessageToUser("Ops, we could not create. Try again later");
			e.printStackTrace();
		}
	}

	public void addDogToPerson() {
		try {
			getPersonFacade().addDogToPerson(dog.getId(), personWithDogs.getId());
			closeDialog();
			displayInfoMessageToUser("Added With Sucess");
			reloadPersonWithDogs();
			resetDog();
		} catch (Exception e) {
			keepDialogOpen();
			displayErrorMessageToUser("Ops, we could not create. Try again later");
			e.printStackTrace();
		}
	}

	public void removeDogFromPerson() {
		try {
			getPersonFacade().removeDogFromPerson(dog.getId(), personWithDogs.getId());
			closeDialog();
			displayInfoMessageToUser("Removed With Sucess");
			reloadPersonWithDogs();
			resetDog();
		} catch (Exception e) {
			keepDialogOpen();
			displayErrorMessageToUser("Ops, we could not create. Try again later");
			e.printStackTrace();
		}
	}

	public Person getPersonWithDogs() {
		if (personWithDogs == null) {
			if (person == null) {
				person = (Person) ELFlash.getFlash().get(SELECTED_PERSON);
			}

			personWithDogs = getPersonFacade().findPersonWithAllDogs(person.getId());
		}

		return personWithDogs;
	}

	public void setPersonWithDogsForDetail(Person person) {
		personWithDogsForDetail = getPersonFacade().findPersonWithAllDogs(person.getId());
	}

	public Person getPersonWithDogsForDetail() {
		if (personWithDogsForDetail == null) {
			personWithDogsForDetail = new Person();
			personWithDogsForDetail.setDogs(new ArrayList<Dog>());
		}

		return personWithDogsForDetail;
	}

	public void resetPersonWithDogsForDetail() {
		personWithDogsForDetail = new Person();
	}

	public String editPersonDogs() {
		ELFlash.getFlash().put(SELECTED_PERSON, person);
		return "/pages/protected/defaultUser/personDogs/personDogs.xhtml";
	}

	public List<Dog> complete(String name) {
		List<Dog> queryResult = new ArrayList<Dog>();

		if (allDogs == null) {
			dogFacade = new DogFacade();
			allDogs = dogFacade.listAll();
		}

		allDogs.removeAll(personWithDogs.getDogs());

		for (Dog dog : allDogs) {
			if (dog.getName().toLowerCase().contains(name.toLowerCase())) {
				queryResult.add(dog);
			}
		}

		return queryResult;
	}

	public PersonFacade getPersonFacade() {
		if (personFacade == null) {
			personFacade = new PersonFacade();
		}

		return personFacade;
	}

	public Person getPerson() {
		if (person == null) {
			person = new Person();
		}

		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public List<Person> getAllPersons() {
		if (persons == null) {
			loadPersons();
		}

		return persons;
	}

	private void loadPersons() {
		persons = getPersonFacade().listAll();
	}

	public void resetPerson() {
		person = new Person();
	}

	public Dog getDog() {
		if (dog == null) {
			dog = new Dog();
		}

		return dog;
	}

	public void setDog(Dog dog) {
		this.dog = dog;
	}

	public void resetDog() {
		dog = new Dog();
	}

	private void reloadPersonWithDogs() {
		personWithDogs = getPersonFacade().findPersonWithAllDogs(person.getId());
	}
}

src/main/webapp/pages/protected/defaultUser/defaultUserIndex.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">
<h:body>
	<ui:composition template="/pages/protected/templates/master.xhtml">
		<ui:define name="divMain">
			<h:form id="personsForm">
				<p:dataTable id="personsTable" value="#{personMB.allPersons}" var="person" emptyMessage="#{bundle.noRecords}" paginator="true" rows="10"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15">
					<p:column>
						<f:facet name="header">
							<h:outputText value="#{bundle.personName}" />
						</f:facet>

						<h:outputText value="#{person.name}" />
					</p:column>

					<p:column>
						<f:facet name="header">
							<h:outputText value="#{bundle.personAge}" />
						</f:facet>

						<h:outputText value="#{person.age}" />
					</p:column>
					<p:column>
						<p:commandButton value="#{bundle.detail}" icon="ui-icon-bullet" onclick="personDetailDialogWidget.show();" update=":personDetailDialogForm" >
							<f:setPropertyActionListener target="#{personMB.personWithDogsForDetail}" value="#{person}" />
						</p:commandButton> 
						<p:spacer width="10px" />
						<p:commandButton value="#{bundle.update}" icon="ui-icon-pencil" update=":personUpdateDialogForm" onclick="personUpdateDialogWidget.show();" >
							<f:setPropertyActionListener target="#{personMB.person}" value="#{person}" />
						</p:commandButton>
						<p:spacer width="10px" />
						<p:commandButton value="#{bundle.delete}" icon="ui-icon-trash" update=":personDeleteDialogForm" onclick="personDeleteDialogWidget.show();" >
							<f:setPropertyActionListener target="#{personMB.person}" value="#{person}" />
						</p:commandButton>
						<p:spacer width="10px" />
						<p:commandButton value="#{bundle.personEditDogs}" icon="ui-icon-contact" ajax="false"
							action="#{personMB.editPersonDogs()}">
								<f:setPropertyActionListener target="#{personMB.person}" value="#{person}" />
						</p:commandButton>
					</p:column>

				</p:dataTable>
				<p:commandButton value="#{bundle.create} #{bundle.person}" icon="ui-icon-plus" update=":personCreateDialogForm"
					actionListener="#{personMB.resetPerson()}" onclick="personCreateDialogWidget.show();" />
			</h:form>

			<ui:include src="/pages/protected/defaultUser/dialogs/personCreateDialog.xhtml" />
			<ui:include src="/pages/protected/defaultUser/dialogs/personUpdateDialog.xhtml" />
			<ui:include src="/pages/protected/defaultUser/dialogs/personDeleteDialog.xhtml" />
			<ui:include src="/pages/protected/defaultUser/dialogs/personDetailDialog.xhtml" />
		</ui:define>
	</ui:composition>
</h:body>
</html>